CREATE TABLE IF NOT EXISTS contact (
    id SERIAL PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    alias VARCHAR(255),
    remark VARCHAR(255),
    nick_name VARCHAR(255),
    is_friend BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);