// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/chatlog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志级别控制
type SetLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // debug, info, warn, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{0}
}

func (x *SetLogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetLogLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelResponse) Reset() {
	*x = SetLogLevelResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelResponse) ProtoMessage() {}

func (x *SetLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelResponse.ProtoReflect.Descriptor instead.
func (*SetLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{1}
}

// Account 信息 (对应 iwechat.Account)
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	FullVersion   string                 `protobuf:"bytes,4,opt,name=full_version,json=fullVersion,proto3" json:"full_version,omitempty"`
	DataDir       string                 `protobuf:"bytes,5,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	ImgKey        string                 `protobuf:"bytes,7,opt,name=img_key,json=imgKey,proto3" json:"img_key,omitempty"`
	Pid           uint32                 `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	ExePath       string                 `protobuf:"bytes,9,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_chatlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Account) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Account) GetFullVersion() string {
	if x != nil {
		return x.FullVersion
	}
	return ""
}

func (x *Account) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Account) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Account) GetImgKey() string {
	if x != nil {
		return x.ImgKey
	}
	return ""
}

func (x *Account) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Account) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// KeyData 响应
type KeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ImgKey        string                 `protobuf:"bytes,2,opt,name=img_key,json=imgKey,proto3" json:"img_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	mi := &file_proto_chatlog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{3}
}

func (x *KeyData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyData) GetImgKey() string {
	if x != nil {
		return x.ImgKey
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{4}
}

func (x *RunRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{5}
}

type SwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *Account               `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	History       string                 `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRequest) Reset() {
	*x = SwitchRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRequest) ProtoMessage() {}

func (x *SwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRequest.ProtoReflect.Descriptor instead.
func (*SwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{6}
}

func (x *SwitchRequest) GetInfo() *Account {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SwitchRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

type SwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchResponse) Reset() {
	*x = SwitchResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchResponse) ProtoMessage() {}

func (x *SwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchResponse.ProtoReflect.Descriptor instead.
func (*SwitchResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{7}
}

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{8}
}

type StartServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceResponse) Reset() {
	*x = StartServiceResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceResponse) ProtoMessage() {}

func (x *StartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceResponse.ProtoReflect.Descriptor instead.
func (*StartServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{9}
}

type StopServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceRequest) Reset() {
	*x = StopServiceRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceRequest) ProtoMessage() {}

func (x *StopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceRequest.ProtoReflect.Descriptor instead.
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{10}
}

type StopServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceResponse) Reset() {
	*x = StopServiceResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceResponse) ProtoMessage() {}

func (x *StopServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceResponse.ProtoReflect.Descriptor instead.
func (*StopServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{11}
}

type SetHTTPAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHTTPAddrRequest) Reset() {
	*x = SetHTTPAddrRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHTTPAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHTTPAddrRequest) ProtoMessage() {}

func (x *SetHTTPAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHTTPAddrRequest.ProtoReflect.Descriptor instead.
func (*SetHTTPAddrRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{12}
}

func (x *SetHTTPAddrRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetHTTPAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHTTPAddrResponse) Reset() {
	*x = SetHTTPAddrResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHTTPAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHTTPAddrResponse) ProtoMessage() {}

func (x *SetHTTPAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHTTPAddrResponse.ProtoReflect.Descriptor instead.
func (*SetHTTPAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{13}
}

type GetDataKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataKeyRequest) Reset() {
	*x = GetDataKeyRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataKeyRequest) ProtoMessage() {}

func (x *GetDataKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataKeyRequest.ProtoReflect.Descriptor instead.
func (*GetDataKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{14}
}

type GetDataKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataKeyResponse) Reset() {
	*x = GetDataKeyResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataKeyResponse) ProtoMessage() {}

func (x *GetDataKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataKeyResponse.ProtoReflect.Descriptor instead.
func (*GetDataKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{15}
}

type DecryptDBFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptDBFilesRequest) Reset() {
	*x = DecryptDBFilesRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptDBFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptDBFilesRequest) ProtoMessage() {}

func (x *DecryptDBFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptDBFilesRequest.ProtoReflect.Descriptor instead.
func (*DecryptDBFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{16}
}

type DecryptDBFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptDBFilesResponse) Reset() {
	*x = DecryptDBFilesResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptDBFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptDBFilesResponse) ProtoMessage() {}

func (x *DecryptDBFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptDBFilesResponse.ProtoReflect.Descriptor instead.
func (*DecryptDBFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{17}
}

type StartAutoDecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAutoDecryptRequest) Reset() {
	*x = StartAutoDecryptRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAutoDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAutoDecryptRequest) ProtoMessage() {}

func (x *StartAutoDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAutoDecryptRequest.ProtoReflect.Descriptor instead.
func (*StartAutoDecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{18}
}

type StartAutoDecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAutoDecryptResponse) Reset() {
	*x = StartAutoDecryptResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAutoDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAutoDecryptResponse) ProtoMessage() {}

func (x *StartAutoDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAutoDecryptResponse.ProtoReflect.Descriptor instead.
func (*StartAutoDecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{19}
}

type StopAutoDecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAutoDecryptRequest) Reset() {
	*x = StopAutoDecryptRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAutoDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAutoDecryptRequest) ProtoMessage() {}

func (x *StopAutoDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAutoDecryptRequest.ProtoReflect.Descriptor instead.
func (*StopAutoDecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{20}
}

type StopAutoDecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAutoDecryptResponse) Reset() {
	*x = StopAutoDecryptResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAutoDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAutoDecryptResponse) ProtoMessage() {}

func (x *StopAutoDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAutoDecryptResponse.ProtoReflect.Descriptor instead.
func (*StopAutoDecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{21}
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{22}
}

type RefreshSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{23}
}

type CommandKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	ShowXorKey    bool                   `protobuf:"varint,4,opt,name=show_xor_key,json=showXorKey,proto3" json:"show_xor_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandKeyRequest) Reset() {
	*x = CommandKeyRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandKeyRequest) ProtoMessage() {}

func (x *CommandKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandKeyRequest.ProtoReflect.Descriptor instead.
func (*CommandKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{24}
}

func (x *CommandKeyRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CommandKeyRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CommandKeyRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *CommandKeyRequest) GetShowXorKey() bool {
	if x != nil {
		return x.ShowXorKey
	}
	return false
}

type CommandKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandKeyResponse) Reset() {
	*x = CommandKeyResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandKeyResponse) ProtoMessage() {}

func (x *CommandKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandKeyResponse.ProtoReflect.Descriptor instead.
func (*CommandKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{25}
}

func (x *CommandKeyResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CommandDecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	CmdConf       map[string]string      `protobuf:"bytes,2,rep,name=cmd_conf,json=cmdConf,proto3" json:"cmd_conf,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDecryptRequest) Reset() {
	*x = CommandDecryptRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDecryptRequest) ProtoMessage() {}

func (x *CommandDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDecryptRequest.ProtoReflect.Descriptor instead.
func (*CommandDecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{26}
}

func (x *CommandDecryptRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CommandDecryptRequest) GetCmdConf() map[string]string {
	if x != nil {
		return x.CmdConf
	}
	return nil
}

type CommandDecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDecryptResponse) Reset() {
	*x = CommandDecryptResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDecryptResponse) ProtoMessage() {}

func (x *CommandDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDecryptResponse.ProtoReflect.Descriptor instead.
func (*CommandDecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{27}
}

type CommandHTTPServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	CmdConf       map[string]string      `protobuf:"bytes,2,rep,name=cmd_conf,json=cmdConf,proto3" json:"cmd_conf,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandHTTPServerRequest) Reset() {
	*x = CommandHTTPServerRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandHTTPServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandHTTPServerRequest) ProtoMessage() {}

func (x *CommandHTTPServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandHTTPServerRequest.ProtoReflect.Descriptor instead.
func (*CommandHTTPServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{28}
}

func (x *CommandHTTPServerRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CommandHTTPServerRequest) GetCmdConf() map[string]string {
	if x != nil {
		return x.CmdConf
	}
	return nil
}

type CommandHTTPServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandHTTPServerResponse) Reset() {
	*x = CommandHTTPServerResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandHTTPServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandHTTPServerResponse) ProtoMessage() {}

func (x *CommandHTTPServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandHTTPServerResponse.ProtoReflect.Descriptor instead.
func (*CommandHTTPServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{29}
}

type GetWeChatInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeChatInstancesRequest) Reset() {
	*x = GetWeChatInstancesRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeChatInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeChatInstancesRequest) ProtoMessage() {}

func (x *GetWeChatInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeChatInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetWeChatInstancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{30}
}

type GetWeChatInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeChatInstancesResponse) Reset() {
	*x = GetWeChatInstancesResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeChatInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeChatInstancesResponse) ProtoMessage() {}

func (x *GetWeChatInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeChatInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetWeChatInstancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{31}
}

func (x *GetWeChatInstancesResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	ShowXorKey    bool                   `protobuf:"varint,4,opt,name=show_xor_key,json=showXorKey,proto3" json:"show_xor_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{32}
}

func (x *GetKeyRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *GetKeyRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GetKeyRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *GetKeyRequest) GetShowXorKey() bool {
	if x != nil {
		return x.ShowXorKey
	}
	return false
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *KeyData               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{33}
}

func (x *GetKeyResponse) GetData() *KeyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	CmdConf       map[string]string      `protobuf:"bytes,2,rep,name=cmd_conf,json=cmdConf,proto3" json:"cmd_conf,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_proto_chatlog_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{34}
}

func (x *DecryptRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *DecryptRequest) GetCmdConf() map[string]string {
	if x != nil {
		return x.CmdConf
	}
	return nil
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_proto_chatlog_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatlog_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatlog_proto_rawDescGZIP(), []int{35}
}

var File_proto_chatlog_proto protoreflect.FileDescriptor

const file_proto_chatlog_proto_rawDesc = "" +
	"\n" +
	"\x13proto/chatlog.proto\x12\x03ipc\"*\n" +
	"\x12SetLogLevelRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"\x15\n" +
	"\x13SetLogLevelResponse\"\x81\x02\n" +
	"\aAccount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12!\n" +
	"\ffull_version\x18\x04 \x01(\tR\vfullVersion\x12\x19\n" +
	"\bdata_dir\x18\x05 \x01(\tR\adataDir\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x17\n" +
	"\aimg_key\x18\a \x01(\tR\x06imgKey\x12\x10\n" +
	"\x03pid\x18\b \x01(\rR\x03pid\x12\x19\n" +
	"\bexe_path\x18\t \x01(\tR\aexePath\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"4\n" +
	"\aKeyData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\aimg_key\x18\x02 \x01(\tR\x06imgKey\"-\n" +
	"\n" +
	"RunRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"\r\n" +
	"\vRunResponse\"K\n" +
	"\rSwitchRequest\x12 \n" +
	"\x04info\x18\x01 \x01(\v2\f.ipc.AccountR\x04info\x12\x18\n" +
	"\ahistory\x18\x02 \x01(\tR\ahistory\"\x10\n" +
	"\x0eSwitchResponse\"\x15\n" +
	"\x13StartServiceRequest\"\x16\n" +
	"\x14StartServiceResponse\"\x14\n" +
	"\x12StopServiceRequest\"\x15\n" +
	"\x13StopServiceResponse\"(\n" +
	"\x12SetHTTPAddrRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x15\n" +
	"\x13SetHTTPAddrResponse\"\x13\n" +
	"\x11GetDataKeyRequest\"\x14\n" +
	"\x12GetDataKeyResponse\"\x17\n" +
	"\x15DecryptDBFilesRequest\"\x18\n" +
	"\x16DecryptDBFilesResponse\"\x19\n" +
	"\x17StartAutoDecryptRequest\"\x1a\n" +
	"\x18StartAutoDecryptResponse\"\x18\n" +
	"\x16StopAutoDecryptRequest\"\x19\n" +
	"\x17StopAutoDecryptResponse\"\x17\n" +
	"\x15RefreshSessionRequest\"\x18\n" +
	"\x16RefreshSessionResponse\"~\n" +
	"\x11CommandKeyRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12 \n" +
	"\fshow_xor_key\x18\x04 \x01(\bR\n" +
	"showXorKey\",\n" +
	"\x12CommandKeyResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xb8\x01\n" +
	"\x15CommandDecryptRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12B\n" +
	"\bcmd_conf\x18\x02 \x03(\v2'.ipc.CommandDecryptRequest.CmdConfEntryR\acmdConf\x1a:\n" +
	"\fCmdConfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16CommandDecryptResponse\"\xbe\x01\n" +
	"\x18CommandHTTPServerRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12E\n" +
	"\bcmd_conf\x18\x02 \x03(\v2*.ipc.CommandHTTPServerRequest.CmdConfEntryR\acmdConf\x1a:\n" +
	"\fCmdConfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\x19CommandHTTPServerResponse\"\x1b\n" +
	"\x19GetWeChatInstancesRequest\"F\n" +
	"\x1aGetWeChatInstancesResponse\x12(\n" +
	"\baccounts\x18\x01 \x03(\v2\f.ipc.AccountR\baccounts\"z\n" +
	"\rGetKeyRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12 \n" +
	"\fshow_xor_key\x18\x04 \x01(\bR\n" +
	"showXorKey\"2\n" +
	"\x0eGetKeyResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.ipc.KeyDataR\x04data\"\xaa\x01\n" +
	"\x0eDecryptRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12;\n" +
	"\bcmd_conf\x18\x02 \x03(\v2 .ipc.DecryptRequest.CmdConfEntryR\acmdConf\x1a:\n" +
	"\fCmdConfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fDecryptResponse2\x8a\t\n" +
	"\x0eManagerService\x12@\n" +
	"\vSetLogLevel\x12\x17.ipc.SetLogLevelRequest\x1a\x18.ipc.SetLogLevelResponse\x12(\n" +
	"\x03Run\x12\x0f.ipc.RunRequest\x1a\x10.ipc.RunResponse\x121\n" +
	"\x06Switch\x12\x12.ipc.SwitchRequest\x1a\x13.ipc.SwitchResponse\x12C\n" +
	"\fStartService\x12\x18.ipc.StartServiceRequest\x1a\x19.ipc.StartServiceResponse\x12@\n" +
	"\vStopService\x12\x17.ipc.StopServiceRequest\x1a\x18.ipc.StopServiceResponse\x12@\n" +
	"\vSetHTTPAddr\x12\x17.ipc.SetHTTPAddrRequest\x1a\x18.ipc.SetHTTPAddrResponse\x12=\n" +
	"\n" +
	"GetDataKey\x12\x16.ipc.GetDataKeyRequest\x1a\x17.ipc.GetDataKeyResponse\x12I\n" +
	"\x0eDecryptDBFiles\x12\x1a.ipc.DecryptDBFilesRequest\x1a\x1b.ipc.DecryptDBFilesResponse\x12O\n" +
	"\x10StartAutoDecrypt\x12\x1c.ipc.StartAutoDecryptRequest\x1a\x1d.ipc.StartAutoDecryptResponse\x12L\n" +
	"\x0fStopAutoDecrypt\x12\x1b.ipc.StopAutoDecryptRequest\x1a\x1c.ipc.StopAutoDecryptResponse\x12I\n" +
	"\x0eRefreshSession\x12\x1a.ipc.RefreshSessionRequest\x1a\x1b.ipc.RefreshSessionResponse\x12=\n" +
	"\n" +
	"CommandKey\x12\x16.ipc.CommandKeyRequest\x1a\x17.ipc.CommandKeyResponse\x12I\n" +
	"\x0eCommandDecrypt\x12\x1a.ipc.CommandDecryptRequest\x1a\x1b.ipc.CommandDecryptResponse\x12R\n" +
	"\x11CommandHTTPServer\x12\x1d.ipc.CommandHTTPServerRequest\x1a\x1e.ipc.CommandHTTPServerResponse\x12U\n" +
	"\x12GetWeChatInstances\x12\x1e.ipc.GetWeChatInstancesRequest\x1a\x1f.ipc.GetWeChatInstancesResponse\x121\n" +
	"\x06GetKey\x12\x12.ipc.GetKeyRequest\x1a\x13.ipc.GetKeyResponse\x124\n" +
	"\aDecrypt\x12\x13.ipc.DecryptRequest\x1a\x14.ipc.DecryptResponseB\x15Z\x13wechat-mem0-core/pbb\x06proto3"

var (
	file_proto_chatlog_proto_rawDescOnce sync.Once
	file_proto_chatlog_proto_rawDescData []byte
)

func file_proto_chatlog_proto_rawDescGZIP() []byte {
	file_proto_chatlog_proto_rawDescOnce.Do(func() {
		file_proto_chatlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chatlog_proto_rawDesc), len(file_proto_chatlog_proto_rawDesc)))
	})
	return file_proto_chatlog_proto_rawDescData
}

var file_proto_chatlog_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_chatlog_proto_goTypes = []any{
	(*SetLogLevelRequest)(nil),         // 0: ipc.SetLogLevelRequest
	(*SetLogLevelResponse)(nil),        // 1: ipc.SetLogLevelResponse
	(*Account)(nil),                    // 2: ipc.Account
	(*KeyData)(nil),                    // 3: ipc.KeyData
	(*RunRequest)(nil),                 // 4: ipc.RunRequest
	(*RunResponse)(nil),                // 5: ipc.RunResponse
	(*SwitchRequest)(nil),              // 6: ipc.SwitchRequest
	(*SwitchResponse)(nil),             // 7: ipc.SwitchResponse
	(*StartServiceRequest)(nil),        // 8: ipc.StartServiceRequest
	(*StartServiceResponse)(nil),       // 9: ipc.StartServiceResponse
	(*StopServiceRequest)(nil),         // 10: ipc.StopServiceRequest
	(*StopServiceResponse)(nil),        // 11: ipc.StopServiceResponse
	(*SetHTTPAddrRequest)(nil),         // 12: ipc.SetHTTPAddrRequest
	(*SetHTTPAddrResponse)(nil),        // 13: ipc.SetHTTPAddrResponse
	(*GetDataKeyRequest)(nil),          // 14: ipc.GetDataKeyRequest
	(*GetDataKeyResponse)(nil),         // 15: ipc.GetDataKeyResponse
	(*DecryptDBFilesRequest)(nil),      // 16: ipc.DecryptDBFilesRequest
	(*DecryptDBFilesResponse)(nil),     // 17: ipc.DecryptDBFilesResponse
	(*StartAutoDecryptRequest)(nil),    // 18: ipc.StartAutoDecryptRequest
	(*StartAutoDecryptResponse)(nil),   // 19: ipc.StartAutoDecryptResponse
	(*StopAutoDecryptRequest)(nil),     // 20: ipc.StopAutoDecryptRequest
	(*StopAutoDecryptResponse)(nil),    // 21: ipc.StopAutoDecryptResponse
	(*RefreshSessionRequest)(nil),      // 22: ipc.RefreshSessionRequest
	(*RefreshSessionResponse)(nil),     // 23: ipc.RefreshSessionResponse
	(*CommandKeyRequest)(nil),          // 24: ipc.CommandKeyRequest
	(*CommandKeyResponse)(nil),         // 25: ipc.CommandKeyResponse
	(*CommandDecryptRequest)(nil),      // 26: ipc.CommandDecryptRequest
	(*CommandDecryptResponse)(nil),     // 27: ipc.CommandDecryptResponse
	(*CommandHTTPServerRequest)(nil),   // 28: ipc.CommandHTTPServerRequest
	(*CommandHTTPServerResponse)(nil),  // 29: ipc.CommandHTTPServerResponse
	(*GetWeChatInstancesRequest)(nil),  // 30: ipc.GetWeChatInstancesRequest
	(*GetWeChatInstancesResponse)(nil), // 31: ipc.GetWeChatInstancesResponse
	(*GetKeyRequest)(nil),              // 32: ipc.GetKeyRequest
	(*GetKeyResponse)(nil),             // 33: ipc.GetKeyResponse
	(*DecryptRequest)(nil),             // 34: ipc.DecryptRequest
	(*DecryptResponse)(nil),            // 35: ipc.DecryptResponse
	nil,                                // 36: ipc.CommandDecryptRequest.CmdConfEntry
	nil,                                // 37: ipc.CommandHTTPServerRequest.CmdConfEntry
	nil,                                // 38: ipc.DecryptRequest.CmdConfEntry
}
var file_proto_chatlog_proto_depIdxs = []int32{
	2,  // 0: ipc.SwitchRequest.info:type_name -> ipc.Account
	36, // 1: ipc.CommandDecryptRequest.cmd_conf:type_name -> ipc.CommandDecryptRequest.CmdConfEntry
	37, // 2: ipc.CommandHTTPServerRequest.cmd_conf:type_name -> ipc.CommandHTTPServerRequest.CmdConfEntry
	2,  // 3: ipc.GetWeChatInstancesResponse.accounts:type_name -> ipc.Account
	3,  // 4: ipc.GetKeyResponse.data:type_name -> ipc.KeyData
	38, // 5: ipc.DecryptRequest.cmd_conf:type_name -> ipc.DecryptRequest.CmdConfEntry
	0,  // 6: ipc.ManagerService.SetLogLevel:input_type -> ipc.SetLogLevelRequest
	4,  // 7: ipc.ManagerService.Run:input_type -> ipc.RunRequest
	6,  // 8: ipc.ManagerService.Switch:input_type -> ipc.SwitchRequest
	8,  // 9: ipc.ManagerService.StartService:input_type -> ipc.StartServiceRequest
	10, // 10: ipc.ManagerService.StopService:input_type -> ipc.StopServiceRequest
	12, // 11: ipc.ManagerService.SetHTTPAddr:input_type -> ipc.SetHTTPAddrRequest
	14, // 12: ipc.ManagerService.GetDataKey:input_type -> ipc.GetDataKeyRequest
	16, // 13: ipc.ManagerService.DecryptDBFiles:input_type -> ipc.DecryptDBFilesRequest
	18, // 14: ipc.ManagerService.StartAutoDecrypt:input_type -> ipc.StartAutoDecryptRequest
	20, // 15: ipc.ManagerService.StopAutoDecrypt:input_type -> ipc.StopAutoDecryptRequest
	22, // 16: ipc.ManagerService.RefreshSession:input_type -> ipc.RefreshSessionRequest
	24, // 17: ipc.ManagerService.CommandKey:input_type -> ipc.CommandKeyRequest
	26, // 18: ipc.ManagerService.CommandDecrypt:input_type -> ipc.CommandDecryptRequest
	28, // 19: ipc.ManagerService.CommandHTTPServer:input_type -> ipc.CommandHTTPServerRequest
	30, // 20: ipc.ManagerService.GetWeChatInstances:input_type -> ipc.GetWeChatInstancesRequest
	32, // 21: ipc.ManagerService.GetKey:input_type -> ipc.GetKeyRequest
	34, // 22: ipc.ManagerService.Decrypt:input_type -> ipc.DecryptRequest
	1,  // 23: ipc.ManagerService.SetLogLevel:output_type -> ipc.SetLogLevelResponse
	5,  // 24: ipc.ManagerService.Run:output_type -> ipc.RunResponse
	7,  // 25: ipc.ManagerService.Switch:output_type -> ipc.SwitchResponse
	9,  // 26: ipc.ManagerService.StartService:output_type -> ipc.StartServiceResponse
	11, // 27: ipc.ManagerService.StopService:output_type -> ipc.StopServiceResponse
	13, // 28: ipc.ManagerService.SetHTTPAddr:output_type -> ipc.SetHTTPAddrResponse
	15, // 29: ipc.ManagerService.GetDataKey:output_type -> ipc.GetDataKeyResponse
	17, // 30: ipc.ManagerService.DecryptDBFiles:output_type -> ipc.DecryptDBFilesResponse
	19, // 31: ipc.ManagerService.StartAutoDecrypt:output_type -> ipc.StartAutoDecryptResponse
	21, // 32: ipc.ManagerService.StopAutoDecrypt:output_type -> ipc.StopAutoDecryptResponse
	23, // 33: ipc.ManagerService.RefreshSession:output_type -> ipc.RefreshSessionResponse
	25, // 34: ipc.ManagerService.CommandKey:output_type -> ipc.CommandKeyResponse
	27, // 35: ipc.ManagerService.CommandDecrypt:output_type -> ipc.CommandDecryptResponse
	29, // 36: ipc.ManagerService.CommandHTTPServer:output_type -> ipc.CommandHTTPServerResponse
	31, // 37: ipc.ManagerService.GetWeChatInstances:output_type -> ipc.GetWeChatInstancesResponse
	33, // 38: ipc.ManagerService.GetKey:output_type -> ipc.GetKeyResponse
	35, // 39: ipc.ManagerService.Decrypt:output_type -> ipc.DecryptResponse
	23, // [23:40] is the sub-list for method output_type
	6,  // [6:23] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_chatlog_proto_init() }
func file_proto_chatlog_proto_init() {
	if File_proto_chatlog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chatlog_proto_rawDesc), len(file_proto_chatlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chatlog_proto_goTypes,
		DependencyIndexes: file_proto_chatlog_proto_depIdxs,
		MessageInfos:      file_proto_chatlog_proto_msgTypes,
	}.Build()
	File_proto_chatlog_proto = out.File
	file_proto_chatlog_proto_goTypes = nil
	file_proto_chatlog_proto_depIdxs = nil
}
